### ISSUE TITLE
Breaking changes tracker

### ISSUE THREAD

**Issue by MattiasMTS** [MattiasMTS/cmp-dbee#28]
I have some more time on my hands now and decided to give this some love.
There is a `ms/v2` branch ready to be used for some new functionalities. I'll add more on this later.

Features in this thread is appreciated ✨ 

Some main ones (perhaps not added to v2)
- [ ] support more completion plugins
    - [x] nvim-cmp
    - [ ] mini.cmp
    - [ ] native completion
    - [ ] coc.nvim
    - [ ] blink.nvim
- [ ] documentation generation
- [ ] tests for regression issues
- [x] column completion with and without alias reference
- [x] completion with multi non-ended sql statements
- [ ] query highlighter (as e.g. jetbrains have for datagrip)
- [ ] make the magic numbers in the code configurable
